[project]
name = "resume-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.123.0",
    "ruff>=0.14.7",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
